//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebServicesASMX.AuthorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AuthorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AuthorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        private double TotalPriceField;
        
        private int QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AuthorId {
            get {
                return this.AuthorIdField;
            }
            set {
                if ((this.AuthorIdField.Equals(value) != true)) {
                    this.AuthorIdField = value;
                    this.RaisePropertyChanged("AuthorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorServiceReference.AuthorSoap")]
    public interface AuthorSoap {
        
        // CODEGEN: Generating message contract since element name GetAuthorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuthors", ReplyAction="*")]
        ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse GetAuthors(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse> GetAuthorsAsync(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SessionValue", ReplyAction="*")]
        int SessionValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SessionValue", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SessionValueAsync();
        
        // CODEGEN: Generating message contract since element name FindResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        ConsumeWebServicesASMX.AuthorServiceReference.FindResponse Find(ConsumeWebServicesASMX.AuthorServiceReference.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindResponse> FindAsync(ConsumeWebServicesASMX.AuthorServiceReference.FindRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (FindAll) of message FindAll does not match the default value (Find1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAll", ReplyAction="*")]
        ConsumeWebServicesASMX.AuthorServiceReference.FindAll1 Find1(ConsumeWebServicesASMX.AuthorServiceReference.FindAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindAll1> Find1Async(ConsumeWebServicesASMX.AuthorServiceReference.FindAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name AuthorName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ConsumeWebServicesASMX.AuthorServiceReference.AddResponse Add(ConsumeWebServicesASMX.AuthorServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.AddResponse> AddAsync(ConsumeWebServicesASMX.AuthorServiceReference.AddRequest request);
        
        // CODEGEN: Generating message contract since element name UpdateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse Update(ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse> UpdateAsync(ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthors", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequestBody Body;
        
        public GetAuthorsRequest() {
        }
        
        public GetAuthorsRequest(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAuthorsRequestBody {
        
        public GetAuthorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponseBody Body;
        
        public GetAuthorsResponse() {
        }
        
        public GetAuthorsResponse(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] GetAuthorsResult;
        
        public GetAuthorsResponseBody() {
        }
        
        public GetAuthorsResponseBody(ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] GetAuthorsResult) {
            this.GetAuthorsResult = GetAuthorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(ConsumeWebServicesASMX.AuthorServiceReference.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(ConsumeWebServicesASMX.AuthorServiceReference.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAll {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public FindAll() {
        }
        
        public FindAll(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAll1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] FindAllResult;
        
        public FindAll1() {
        }
        
        public FindAll1(ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] FindAllResult) {
            this.FindAllResult = FindAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ConsumeWebServicesASMX.AuthorServiceReference.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Active;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string AuthorName, string Gender, bool Active) {
            this.AuthorName = AuthorName;
            this.Gender = Gender;
            this.Active = Active;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ConsumeWebServicesASMX.AuthorServiceReference.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRequestBody {
        
        public UpdateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthorSoapChannel : ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorSoapClient : System.ServiceModel.ClientBase<ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap>, ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap {
        
        public AuthorSoapClient() {
        }
        
        public AuthorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.GetAuthors(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest request) {
            return base.Channel.GetAuthors(request);
        }
        
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] GetAuthors() {
            ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequestBody();
            ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse retVal = ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).GetAuthors(inValue);
            return retVal.Body.GetAuthorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse> ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.GetAuthorsAsync(ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest request) {
            return base.Channel.GetAuthorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsResponse> GetAuthorsAsync() {
            ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.GetAuthorsRequestBody();
            return ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).GetAuthorsAsync(inValue);
        }
        
        public int SessionValue() {
            return base.Channel.SessionValue();
        }
        
        public System.Threading.Tasks.Task<int> SessionValueAsync() {
            return base.Channel.SessionValueAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebServicesASMX.AuthorServiceReference.FindResponse ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.Find(ConsumeWebServicesASMX.AuthorServiceReference.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel Find(int id) {
            ConsumeWebServicesASMX.AuthorServiceReference.FindRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.FindRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.FindRequestBody();
            inValue.Body.id = id;
            ConsumeWebServicesASMX.AuthorServiceReference.FindResponse retVal = ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindResponse> ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.FindAsync(ConsumeWebServicesASMX.AuthorServiceReference.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindResponse> FindAsync(int id) {
            ConsumeWebServicesASMX.AuthorServiceReference.FindRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.FindRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.FindRequestBody();
            inValue.Body.id = id;
            return ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebServicesASMX.AuthorServiceReference.FindAll1 ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.Find1(ConsumeWebServicesASMX.AuthorServiceReference.FindAll request) {
            return base.Channel.Find1(request);
        }
        
        public ConsumeWebServicesASMX.AuthorServiceReference.AuthorModel[] Find1(string name) {
            ConsumeWebServicesASMX.AuthorServiceReference.FindAll inValue = new ConsumeWebServicesASMX.AuthorServiceReference.FindAll();
            inValue.name = name;
            ConsumeWebServicesASMX.AuthorServiceReference.FindAll1 retVal = ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).Find1(inValue);
            return retVal.FindAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindAll1> ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.Find1Async(ConsumeWebServicesASMX.AuthorServiceReference.FindAll request) {
            return base.Channel.Find1Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.FindAll1> Find1Async(string name) {
            ConsumeWebServicesASMX.AuthorServiceReference.FindAll inValue = new ConsumeWebServicesASMX.AuthorServiceReference.FindAll();
            inValue.name = name;
            return ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).Find1Async(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebServicesASMX.AuthorServiceReference.AddResponse ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.Add(ConsumeWebServicesASMX.AuthorServiceReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(string AuthorName, string Gender, bool Active) {
            ConsumeWebServicesASMX.AuthorServiceReference.AddRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.AddRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.AddRequestBody();
            inValue.Body.AuthorName = AuthorName;
            inValue.Body.Gender = Gender;
            inValue.Body.Active = Active;
            ConsumeWebServicesASMX.AuthorServiceReference.AddResponse retVal = ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.AddResponse> ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.AddAsync(ConsumeWebServicesASMX.AuthorServiceReference.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.AddResponse> AddAsync(string AuthorName, string Gender, bool Active) {
            ConsumeWebServicesASMX.AuthorServiceReference.AddRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.AddRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.AddRequestBody();
            inValue.Body.AuthorName = AuthorName;
            inValue.Body.Gender = Gender;
            inValue.Body.Active = Active;
            return ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.Update(ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update() {
            ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequestBody();
            ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse retVal = ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse> ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap.UpdateAsync(ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebServicesASMX.AuthorServiceReference.UpdateResponse> UpdateAsync() {
            ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest inValue = new ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequest();
            inValue.Body = new ConsumeWebServicesASMX.AuthorServiceReference.UpdateRequestBody();
            return ((ConsumeWebServicesASMX.AuthorServiceReference.AuthorSoap)(this)).UpdateAsync(inValue);
        }
    }
}
